//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.08 at 11:09:32 AM CEST 
//


package rs.xml.oglas.xsdgenerated;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Cenovnik complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Cenovnik"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="cid" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="cenaZaDan" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="cenaPoKilometru" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="cenaOsiguranja" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="popust" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="zaViseOd" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="username" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Cenovnik", propOrder = {
    "cid",
    "name",
    "cenaZaDan",
    "cenaPoKilometru",
    "cenaOsiguranja",
    "popust",
    "zaViseOd",
    "username"
})
public class Cenovnik {

    @XmlElement(required = true)
    protected String cid;
    @XmlElement(required = true)
    protected String name;
    protected int cenaZaDan;
    protected int cenaPoKilometru;
    protected int cenaOsiguranja;
    protected int popust;
    protected int zaViseOd;
    @XmlElement(required = true)
    protected String username;

    /**
     * Gets the value of the cid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCid() {
        return cid;
    }

    /**
     * Sets the value of the cid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCid(String value) {
        this.cid = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the cenaZaDan property.
     * 
     */
    public int getCenaZaDan() {
        return cenaZaDan;
    }

    /**
     * Sets the value of the cenaZaDan property.
     * 
     */
    public void setCenaZaDan(int value) {
        this.cenaZaDan = value;
    }

    /**
     * Gets the value of the cenaPoKilometru property.
     * 
     */
    public int getCenaPoKilometru() {
        return cenaPoKilometru;
    }

    /**
     * Sets the value of the cenaPoKilometru property.
     * 
     */
    public void setCenaPoKilometru(int value) {
        this.cenaPoKilometru = value;
    }

    /**
     * Gets the value of the cenaOsiguranja property.
     * 
     */
    public int getCenaOsiguranja() {
        return cenaOsiguranja;
    }

    /**
     * Sets the value of the cenaOsiguranja property.
     * 
     */
    public void setCenaOsiguranja(int value) {
        this.cenaOsiguranja = value;
    }

    /**
     * Gets the value of the popust property.
     * 
     */
    public int getPopust() {
        return popust;
    }

    /**
     * Sets the value of the popust property.
     * 
     */
    public void setPopust(int value) {
        this.popust = value;
    }

    /**
     * Gets the value of the zaViseOd property.
     * 
     */
    public int getZaViseOd() {
        return zaViseOd;
    }

    /**
     * Sets the value of the zaViseOd property.
     * 
     */
    public void setZaViseOd(int value) {
        this.zaViseOd = value;
    }

    /**
     * Gets the value of the username property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUsername() {
        return username;
    }

    /**
     * Sets the value of the username property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUsername(String value) {
        this.username = value;
    }

}
