//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.19 at 05:44:53 PM CEST 
//


package rs.xml.oglas.xsd;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the rs.xml.oglas.xsd package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rs.xml.oglas.xsd
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PostOglasRequest }
     * 
     */
    public PostOglasRequest createPostOglasRequest() {
        return new PostOglasRequest();
    }

    /**
     * Create an instance of {@link Oglas }
     * 
     */
    public Oglas createOglas() {
        return new Oglas();
    }

    /**
     * Create an instance of {@link PostOglasResponse }
     * 
     */
    public PostOglasResponse createPostOglasResponse() {
        return new PostOglasResponse();
    }

    /**
     * Create an instance of {@link PostZahtevRequest }
     * 
     */
    public PostZahtevRequest createPostZahtevRequest() {
        return new PostZahtevRequest();
    }

    /**
     * Create an instance of {@link Zahtev }
     * 
     */
    public Zahtev createZahtev() {
        return new Zahtev();
    }

    /**
     * Create an instance of {@link PostZahtevResponse }
     * 
     */
    public PostZahtevResponse createPostZahtevResponse() {
        return new PostZahtevResponse();
    }

    /**
     * Create an instance of {@link PostOcenaRequest }
     * 
     */
    public PostOcenaRequest createPostOcenaRequest() {
        return new PostOcenaRequest();
    }

    /**
     * Create an instance of {@link Ocena }
     * 
     */
    public Ocena createOcena() {
        return new Ocena();
    }

    /**
     * Create an instance of {@link PostOcenaResponse }
     * 
     */
    public PostOcenaResponse createPostOcenaResponse() {
        return new PostOcenaResponse();
    }

    /**
     * Create an instance of {@link PostIzvestajRequest }
     * 
     */
    public PostIzvestajRequest createPostIzvestajRequest() {
        return new PostIzvestajRequest();
    }

    /**
     * Create an instance of {@link Izvestaj }
     * 
     */
    public Izvestaj createIzvestaj() {
        return new Izvestaj();
    }

    /**
     * Create an instance of {@link PostIzvestajResponse }
     * 
     */
    public PostIzvestajResponse createPostIzvestajResponse() {
        return new PostIzvestajResponse();
    }

    /**
     * Create an instance of {@link GetEverythingRequest }
     * 
     */
    public GetEverythingRequest createGetEverythingRequest() {
        return new GetEverythingRequest();
    }

    /**
     * Create an instance of {@link GetEverythingResponse }
     * 
     */
    public GetEverythingResponse createGetEverythingResponse() {
        return new GetEverythingResponse();
    }

    /**
     * Create an instance of {@link Chat }
     * 
     */
    public Chat createChat() {
        return new Chat();
    }

    /**
     * Create an instance of {@link Slika }
     * 
     */
    public Slika createSlika() {
        return new Slika();
    }

    /**
     * Create an instance of {@link OglasUZahtevu }
     * 
     */
    public OglasUZahtevu createOglasUZahtevu() {
        return new OglasUZahtevu();
    }

    /**
     * Create an instance of {@link Poruka }
     * 
     */
    public Poruka createPoruka() {
        return new Poruka();
    }

}
